name: TWoNResourcePackHandler
main: me.AxiusDevelopment.TWoNResourePackHandler.TWoNResourcePackHandler
author: AxiusDevelopment
version: 1.8
commands:
    pack:
        description: send yourself a link to the pack.
    pack-reload:
        description: reload plugin YAML files.
    pack-send:
        description: send the resource pack to a player.
    pack-add:
        description: add a URl to the server via worlds.








